-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity downsample is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    stream_in_48_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    stream_in_48_TVALID : IN STD_LOGIC;
    stream_in_48_TREADY : OUT STD_LOGIC;
    stream_in_48_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    stream_in_48_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    stream_in_48_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_48_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_out_48_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    stream_out_48_TVALID : OUT STD_LOGIC;
    stream_out_48_TREADY : IN STD_LOGIC;
    stream_out_48_TKEEP : OUT STD_LOGIC_VECTOR (7 downto 0);
    stream_out_48_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    stream_out_48_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_48_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of downsample is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "downsample_downsample,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.254000,HLS_SYN_LAT=375065,HLS_SYN_TPT=none,HLS_SYN_MEM=1408,HLS_SYN_DSP=0,HLS_SYN_FF=3077,HLS_SYN_LUT=2957,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal image_block_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal image_block_ce0 : STD_LOGIC;
    signal image_block_we0 : STD_LOGIC;
    signal image_block_q0 : STD_LOGIC_VECTOR (47 downto 0);
    signal image_block_ce1 : STD_LOGIC;
    signal image_block_q1 : STD_LOGIC_VECTOR (47 downto 0);
    signal image_block_1_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal image_block_1_ce0 : STD_LOGIC;
    signal image_block_1_we0 : STD_LOGIC;
    signal image_block_1_q0 : STD_LOGIC_VECTOR (47 downto 0);
    signal image_block_1_ce1 : STD_LOGIC;
    signal image_block_1_q1 : STD_LOGIC_VECTOR (47 downto 0);
    signal image_block_2_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal image_block_2_ce0 : STD_LOGIC;
    signal image_block_2_we0 : STD_LOGIC;
    signal image_block_2_q0 : STD_LOGIC_VECTOR (47 downto 0);
    signal image_block_2_ce1 : STD_LOGIC;
    signal image_block_2_q1 : STD_LOGIC_VECTOR (47 downto 0);
    signal downsample_block_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal downsample_block_ce0 : STD_LOGIC;
    signal downsample_block_we0 : STD_LOGIC_VECTOR (7 downto 0);
    signal downsample_block_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_start : STD_LOGIC;
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_done : STD_LOGIC;
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_idle : STD_LOGIC;
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_ready : STD_LOGIC;
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_ce0 : STD_LOGIC;
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_we0 : STD_LOGIC;
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_d0 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_ce0 : STD_LOGIC;
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_we0 : STD_LOGIC;
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_d0 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_ce0 : STD_LOGIC;
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_we0 : STD_LOGIC;
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_d0 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_stream_in_48_TREADY : STD_LOGIC;
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_start : STD_LOGIC;
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_done : STD_LOGIC;
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_idle : STD_LOGIC;
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_ready : STD_LOGIC;
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_ce0 : STD_LOGIC;
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_address1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_ce1 : STD_LOGIC;
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_ce0 : STD_LOGIC;
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_address1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_ce1 : STD_LOGIC;
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_ce0 : STD_LOGIC;
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_address1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_ce1 : STD_LOGIC;
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_ce0 : STD_LOGIC;
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_we0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_start : STD_LOGIC;
    signal grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_done : STD_LOGIC;
    signal grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_idle : STD_LOGIC;
    signal grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_ready : STD_LOGIC;
    signal grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TREADY : STD_LOGIC;
    signal grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_downsample_block_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_downsample_block_ce0 : STD_LOGIC;
    signal grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TVALID : STD_LOGIC;
    signal grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TKEEP : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm_state2 : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal regslice_both_stream_out_48_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal regslice_both_stream_in_48_V_data_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_48_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal stream_in_48_TVALID_int_regslice : STD_LOGIC;
    signal stream_in_48_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_stream_in_48_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_48_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_48_TKEEP_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_stream_in_48_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_48_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_48_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_48_TSTRB_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_stream_in_48_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_48_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_48_V_user_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_48_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_in_48_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_48_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_48_V_last_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_48_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_in_48_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_48_V_last_V_U_ack_in : STD_LOGIC;
    signal stream_out_48_TVALID_int_regslice : STD_LOGIC;
    signal stream_out_48_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_stream_out_48_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_48_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_48_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_48_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_48_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_48_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_48_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_48_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_48_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_48_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_48_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_48_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_48_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component downsample_downsample_Pipeline_read_image_VITIS_LOOP_59_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_in_48_TVALID : IN STD_LOGIC;
        image_block_2_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        image_block_2_ce0 : OUT STD_LOGIC;
        image_block_2_we0 : OUT STD_LOGIC;
        image_block_2_d0 : OUT STD_LOGIC_VECTOR (47 downto 0);
        image_block_1_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        image_block_1_ce0 : OUT STD_LOGIC;
        image_block_1_we0 : OUT STD_LOGIC;
        image_block_1_d0 : OUT STD_LOGIC_VECTOR (47 downto 0);
        image_block_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        image_block_ce0 : OUT STD_LOGIC;
        image_block_we0 : OUT STD_LOGIC;
        image_block_d0 : OUT STD_LOGIC_VECTOR (47 downto 0);
        stream_in_48_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        stream_in_48_TREADY : OUT STD_LOGIC;
        stream_in_48_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
        stream_in_48_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        stream_in_48_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_in_48_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component downsample_downsample_Pipeline_downsample_VITIS_LOOP_66_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        image_block_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        image_block_ce0 : OUT STD_LOGIC;
        image_block_q0 : IN STD_LOGIC_VECTOR (47 downto 0);
        image_block_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        image_block_ce1 : OUT STD_LOGIC;
        image_block_q1 : IN STD_LOGIC_VECTOR (47 downto 0);
        image_block_1_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        image_block_1_ce0 : OUT STD_LOGIC;
        image_block_1_q0 : IN STD_LOGIC_VECTOR (47 downto 0);
        image_block_1_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        image_block_1_ce1 : OUT STD_LOGIC;
        image_block_1_q1 : IN STD_LOGIC_VECTOR (47 downto 0);
        image_block_2_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        image_block_2_ce0 : OUT STD_LOGIC;
        image_block_2_q0 : IN STD_LOGIC_VECTOR (47 downto 0);
        image_block_2_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        image_block_2_ce1 : OUT STD_LOGIC;
        image_block_2_q1 : IN STD_LOGIC_VECTOR (47 downto 0);
        downsample_block_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        downsample_block_ce0 : OUT STD_LOGIC;
        downsample_block_we0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        downsample_block_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component downsample_downsample_Pipeline_write_image_VITIS_LOOP_74_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_out_48_TREADY : IN STD_LOGIC;
        downsample_block_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        downsample_block_ce0 : OUT STD_LOGIC;
        downsample_block_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        stream_out_48_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        stream_out_48_TVALID : OUT STD_LOGIC;
        stream_out_48_TKEEP : OUT STD_LOGIC_VECTOR (7 downto 0);
        stream_out_48_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        stream_out_48_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        stream_out_48_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component downsample_image_block_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (47 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (47 downto 0);
        address1 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component downsample_downsample_block_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC_VECTOR (7 downto 0);
        d0 : IN STD_LOGIC_VECTOR (63 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component downsample_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    image_block_U : component downsample_image_block_RAM_AUTO_1R1W
    generic map (
        DataWidth => 48,
        AddressRange => 83334,
        AddressWidth => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => image_block_address0,
        ce0 => image_block_ce0,
        we0 => image_block_we0,
        d0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_d0,
        q0 => image_block_q0,
        address1 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_address1,
        ce1 => image_block_ce1,
        q1 => image_block_q1);

    image_block_1_U : component downsample_image_block_RAM_AUTO_1R1W
    generic map (
        DataWidth => 48,
        AddressRange => 83334,
        AddressWidth => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => image_block_1_address0,
        ce0 => image_block_1_ce0,
        we0 => image_block_1_we0,
        d0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_d0,
        q0 => image_block_1_q0,
        address1 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_address1,
        ce1 => image_block_1_ce1,
        q1 => image_block_1_q1);

    image_block_2_U : component downsample_image_block_RAM_AUTO_1R1W
    generic map (
        DataWidth => 48,
        AddressRange => 83334,
        AddressWidth => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => image_block_2_address0,
        ce0 => image_block_2_ce0,
        we0 => image_block_2_we0,
        d0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_d0,
        q0 => image_block_2_q0,
        address1 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_address1,
        ce1 => image_block_2_ce1,
        q1 => image_block_2_q1);

    downsample_block_U : component downsample_downsample_block_RAM_AUTO_1R1W
    generic map (
        DataWidth => 64,
        AddressRange => 62500,
        AddressWidth => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => downsample_block_address0,
        ce0 => downsample_block_ce0,
        we0 => downsample_block_we0,
        d0 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_d0,
        q0 => downsample_block_q0);

    grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78 : component downsample_downsample_Pipeline_read_image_VITIS_LOOP_59_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_start,
        ap_done => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_done,
        ap_idle => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_idle,
        ap_ready => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_ready,
        stream_in_48_TVALID => stream_in_48_TVALID_int_regslice,
        image_block_2_address0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_address0,
        image_block_2_ce0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_ce0,
        image_block_2_we0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_we0,
        image_block_2_d0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_d0,
        image_block_1_address0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_address0,
        image_block_1_ce0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_ce0,
        image_block_1_we0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_we0,
        image_block_1_d0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_d0,
        image_block_address0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_address0,
        image_block_ce0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_ce0,
        image_block_we0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_we0,
        image_block_d0 => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_d0,
        stream_in_48_TDATA => stream_in_48_TDATA_int_regslice,
        stream_in_48_TREADY => grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_stream_in_48_TREADY,
        stream_in_48_TKEEP => stream_in_48_TKEEP_int_regslice,
        stream_in_48_TSTRB => stream_in_48_TSTRB_int_regslice,
        stream_in_48_TUSER => stream_in_48_TUSER_int_regslice,
        stream_in_48_TLAST => stream_in_48_TLAST_int_regslice);

    grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95 : component downsample_downsample_Pipeline_downsample_VITIS_LOOP_66_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_start,
        ap_done => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_done,
        ap_idle => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_idle,
        ap_ready => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_ready,
        image_block_address0 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_address0,
        image_block_ce0 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_ce0,
        image_block_q0 => image_block_q0,
        image_block_address1 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_address1,
        image_block_ce1 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_ce1,
        image_block_q1 => image_block_q1,
        image_block_1_address0 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_address0,
        image_block_1_ce0 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_ce0,
        image_block_1_q0 => image_block_1_q0,
        image_block_1_address1 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_address1,
        image_block_1_ce1 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_ce1,
        image_block_1_q1 => image_block_1_q1,
        image_block_2_address0 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_address0,
        image_block_2_ce0 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_ce0,
        image_block_2_q0 => image_block_2_q0,
        image_block_2_address1 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_address1,
        image_block_2_ce1 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_ce1,
        image_block_2_q1 => image_block_2_q1,
        downsample_block_address0 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_address0,
        downsample_block_ce0 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_ce0,
        downsample_block_we0 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_we0,
        downsample_block_d0 => grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_d0);

    grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103 : component downsample_downsample_Pipeline_write_image_VITIS_LOOP_74_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_start,
        ap_done => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_done,
        ap_idle => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_idle,
        ap_ready => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_ready,
        stream_out_48_TREADY => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TREADY,
        downsample_block_address0 => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_downsample_block_address0,
        downsample_block_ce0 => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_downsample_block_ce0,
        downsample_block_q0 => downsample_block_q0,
        stream_out_48_TDATA => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TDATA,
        stream_out_48_TVALID => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TVALID,
        stream_out_48_TKEEP => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TKEEP,
        stream_out_48_TSTRB => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TSTRB,
        stream_out_48_TUSER => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TUSER,
        stream_out_48_TLAST => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TLAST);

    regslice_both_stream_in_48_V_data_V_U : component downsample_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_48_TDATA,
        vld_in => stream_in_48_TVALID,
        ack_in => regslice_both_stream_in_48_V_data_V_U_ack_in,
        data_out => stream_in_48_TDATA_int_regslice,
        vld_out => stream_in_48_TVALID_int_regslice,
        ack_out => stream_in_48_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_48_V_data_V_U_apdone_blk);

    regslice_both_stream_in_48_V_keep_V_U : component downsample_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_48_TKEEP,
        vld_in => stream_in_48_TVALID,
        ack_in => regslice_both_stream_in_48_V_keep_V_U_ack_in,
        data_out => stream_in_48_TKEEP_int_regslice,
        vld_out => regslice_both_stream_in_48_V_keep_V_U_vld_out,
        ack_out => stream_in_48_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_48_V_keep_V_U_apdone_blk);

    regslice_both_stream_in_48_V_strb_V_U : component downsample_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_48_TSTRB,
        vld_in => stream_in_48_TVALID,
        ack_in => regslice_both_stream_in_48_V_strb_V_U_ack_in,
        data_out => stream_in_48_TSTRB_int_regslice,
        vld_out => regslice_both_stream_in_48_V_strb_V_U_vld_out,
        ack_out => stream_in_48_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_48_V_strb_V_U_apdone_blk);

    regslice_both_stream_in_48_V_user_V_U : component downsample_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_48_TUSER,
        vld_in => stream_in_48_TVALID,
        ack_in => regslice_both_stream_in_48_V_user_V_U_ack_in,
        data_out => stream_in_48_TUSER_int_regslice,
        vld_out => regslice_both_stream_in_48_V_user_V_U_vld_out,
        ack_out => stream_in_48_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_48_V_user_V_U_apdone_blk);

    regslice_both_stream_in_48_V_last_V_U : component downsample_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_48_TLAST,
        vld_in => stream_in_48_TVALID,
        ack_in => regslice_both_stream_in_48_V_last_V_U_ack_in,
        data_out => stream_in_48_TLAST_int_regslice,
        vld_out => regslice_both_stream_in_48_V_last_V_U_vld_out,
        ack_out => stream_in_48_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_48_V_last_V_U_apdone_blk);

    regslice_both_stream_out_48_V_data_V_U : component downsample_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TDATA,
        vld_in => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TVALID,
        ack_in => stream_out_48_TREADY_int_regslice,
        data_out => stream_out_48_TDATA,
        vld_out => regslice_both_stream_out_48_V_data_V_U_vld_out,
        ack_out => stream_out_48_TREADY,
        apdone_blk => regslice_both_stream_out_48_V_data_V_U_apdone_blk);

    regslice_both_stream_out_48_V_keep_V_U : component downsample_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TKEEP,
        vld_in => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TVALID,
        ack_in => regslice_both_stream_out_48_V_keep_V_U_ack_in_dummy,
        data_out => stream_out_48_TKEEP,
        vld_out => regslice_both_stream_out_48_V_keep_V_U_vld_out,
        ack_out => stream_out_48_TREADY,
        apdone_blk => regslice_both_stream_out_48_V_keep_V_U_apdone_blk);

    regslice_both_stream_out_48_V_strb_V_U : component downsample_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TSTRB,
        vld_in => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TVALID,
        ack_in => regslice_both_stream_out_48_V_strb_V_U_ack_in_dummy,
        data_out => stream_out_48_TSTRB,
        vld_out => regslice_both_stream_out_48_V_strb_V_U_vld_out,
        ack_out => stream_out_48_TREADY,
        apdone_blk => regslice_both_stream_out_48_V_strb_V_U_apdone_blk);

    regslice_both_stream_out_48_V_user_V_U : component downsample_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TUSER,
        vld_in => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TVALID,
        ack_in => regslice_both_stream_out_48_V_user_V_U_ack_in_dummy,
        data_out => stream_out_48_TUSER,
        vld_out => regslice_both_stream_out_48_V_user_V_U_vld_out,
        ack_out => stream_out_48_TREADY,
        apdone_blk => regslice_both_stream_out_48_V_user_V_U_apdone_blk);

    regslice_both_stream_out_48_V_last_V_U : component downsample_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TLAST,
        vld_in => grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TVALID,
        ack_in => regslice_both_stream_out_48_V_last_V_U_ack_in_dummy,
        data_out => stream_out_48_TLAST,
        vld_out => regslice_both_stream_out_48_V_last_V_U_vld_out,
        ack_out => stream_out_48_TREADY,
        apdone_blk => regslice_both_stream_out_48_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_ready = ap_const_logic_1)) then 
                    grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_ready = ap_const_logic_1)) then 
                    grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_ready = ap_const_logic_1)) then 
                    grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_done, grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_done, grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_done, ap_CS_fsm, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7, regslice_both_stream_out_48_V_data_V_U_apdone_blk, ap_CS_fsm_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((regslice_both_stream_out_48_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_NS_fsm_state2 <= ap_NS_fsm(1);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_done)
    begin
        if ((grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_done)
    begin
        if ((grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_done)
    begin
        if ((grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state8_blk_assign_proc : process(regslice_both_stream_out_48_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_stream_out_48_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    downsample_block_address0_assign_proc : process(grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_address0, grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_downsample_block_address0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            downsample_block_address0 <= grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_downsample_block_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            downsample_block_address0 <= grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_address0;
        else 
            downsample_block_address0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    downsample_block_ce0_assign_proc : process(grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_ce0, grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_downsample_block_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            downsample_block_ce0 <= grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_downsample_block_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            downsample_block_ce0 <= grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_ce0;
        else 
            downsample_block_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    downsample_block_we0_assign_proc : process(grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            downsample_block_we0 <= grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_downsample_block_we0;
        else 
            downsample_block_we0 <= (0=>ap_const_logic_0, others=>'-');
        end if; 
    end process;

    grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_start <= grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_ap_start_reg;
    grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_start <= grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_ap_start_reg;
    grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_start <= grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_ap_start_reg;
    grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TREADY <= (stream_out_48_TREADY_int_regslice and ap_CS_fsm_state7);

    image_block_1_address0_assign_proc : process(grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_address0, grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            image_block_1_address0 <= grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            image_block_1_address0 <= grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_address0;
        else 
            image_block_1_address0 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    image_block_1_ce0_assign_proc : process(grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_ce0, grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            image_block_1_ce0 <= grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            image_block_1_ce0 <= grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_ce0;
        else 
            image_block_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    image_block_1_ce1_assign_proc : process(grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            image_block_1_ce1 <= grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_1_ce1;
        else 
            image_block_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    image_block_1_we0_assign_proc : process(grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            image_block_1_we0 <= grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_1_we0;
        else 
            image_block_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    image_block_2_address0_assign_proc : process(grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_address0, grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            image_block_2_address0 <= grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            image_block_2_address0 <= grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_address0;
        else 
            image_block_2_address0 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    image_block_2_ce0_assign_proc : process(grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_ce0, grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            image_block_2_ce0 <= grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            image_block_2_ce0 <= grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_ce0;
        else 
            image_block_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    image_block_2_ce1_assign_proc : process(grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            image_block_2_ce1 <= grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_2_ce1;
        else 
            image_block_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    image_block_2_we0_assign_proc : process(grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            image_block_2_we0 <= grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_2_we0;
        else 
            image_block_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    image_block_address0_assign_proc : process(grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_address0, grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            image_block_address0 <= grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            image_block_address0 <= grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_address0;
        else 
            image_block_address0 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    image_block_ce0_assign_proc : process(grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_ce0, grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            image_block_ce0 <= grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            image_block_ce0 <= grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_ce0;
        else 
            image_block_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    image_block_ce1_assign_proc : process(grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            image_block_ce1 <= grp_downsample_Pipeline_downsample_VITIS_LOOP_66_2_fu_95_image_block_ce1;
        else 
            image_block_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    image_block_we0_assign_proc : process(grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            image_block_we0 <= grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_image_block_we0;
        else 
            image_block_we0 <= ap_const_logic_0;
        end if; 
    end process;

    stream_in_48_TREADY <= regslice_both_stream_in_48_V_data_V_U_ack_in;

    stream_in_48_TREADY_int_regslice_assign_proc : process(grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_stream_in_48_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            stream_in_48_TREADY_int_regslice <= grp_downsample_Pipeline_read_image_VITIS_LOOP_59_1_fu_78_stream_in_48_TREADY;
        else 
            stream_in_48_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    stream_out_48_TVALID <= regslice_both_stream_out_48_V_data_V_U_vld_out;
    stream_out_48_TVALID_int_regslice <= grp_downsample_Pipeline_write_image_VITIS_LOOP_74_3_fu_103_stream_out_48_TVALID;
end behav;
