// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module IMG2RLE_IMG2RLE_Pipeline_L1_L24 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dct_middle_2_address0,
        dct_middle_2_ce0,
        dct_middle_2_we0,
        dct_middle_2_d0,
        dct_middle_2_address1,
        dct_middle_2_ce1,
        dct_middle_2_q1,
        Cr_address0,
        Cr_ce0,
        Cr_q0,
        Cr_1_address0,
        Cr_1_ce0,
        Cr_1_q0,
        Cr_2_address0,
        Cr_2_ce0,
        Cr_2_q0,
        Cr_3_address0,
        Cr_3_ce0,
        Cr_3_q0,
        Cr_4_address0,
        Cr_4_ce0,
        Cr_4_q0,
        Cr_5_address0,
        Cr_5_ce0,
        Cr_5_q0,
        Cr_6_address0,
        Cr_6_ce0,
        Cr_6_q0,
        Cr_7_address0,
        Cr_7_ce0,
        Cr_7_q0,
        dct12_i_0_address0,
        dct12_i_0_ce0,
        dct12_i_0_q0,
        dct12_i_1_address0,
        dct12_i_1_ce0,
        dct12_i_1_q0,
        dct12_i_2_address0,
        dct12_i_2_ce0,
        dct12_i_2_q0,
        dct12_i_3_address0,
        dct12_i_3_ce0,
        dct12_i_3_q0,
        dct12_i_4_address0,
        dct12_i_4_ce0,
        dct12_i_4_q0,
        dct12_i_5_address0,
        dct12_i_5_ce0,
        dct12_i_5_q0,
        dct12_i_6_address0,
        dct12_i_6_ce0,
        dct12_i_6_q0,
        dct12_i_7_address0,
        dct12_i_7_ce0,
        dct12_i_7_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] dct_middle_2_address0;
output   dct_middle_2_ce0;
output   dct_middle_2_we0;
output  [17:0] dct_middle_2_d0;
output  [5:0] dct_middle_2_address1;
output   dct_middle_2_ce1;
input  [17:0] dct_middle_2_q1;
output  [2:0] Cr_address0;
output   Cr_ce0;
input  [7:0] Cr_q0;
output  [2:0] Cr_1_address0;
output   Cr_1_ce0;
input  [7:0] Cr_1_q0;
output  [2:0] Cr_2_address0;
output   Cr_2_ce0;
input  [7:0] Cr_2_q0;
output  [2:0] Cr_3_address0;
output   Cr_3_ce0;
input  [7:0] Cr_3_q0;
output  [2:0] Cr_4_address0;
output   Cr_4_ce0;
input  [7:0] Cr_4_q0;
output  [2:0] Cr_5_address0;
output   Cr_5_ce0;
input  [7:0] Cr_5_q0;
output  [2:0] Cr_6_address0;
output   Cr_6_ce0;
input  [7:0] Cr_6_q0;
output  [2:0] Cr_7_address0;
output   Cr_7_ce0;
input  [7:0] Cr_7_q0;
output  [2:0] dct12_i_0_address0;
output   dct12_i_0_ce0;
input  [10:0] dct12_i_0_q0;
output  [2:0] dct12_i_1_address0;
output   dct12_i_1_ce0;
input  [11:0] dct12_i_1_q0;
output  [2:0] dct12_i_2_address0;
output   dct12_i_2_ce0;
input  [11:0] dct12_i_2_q0;
output  [2:0] dct12_i_3_address0;
output   dct12_i_3_ce0;
input  [11:0] dct12_i_3_q0;
output  [2:0] dct12_i_4_address0;
output   dct12_i_4_ce0;
input  [11:0] dct12_i_4_q0;
output  [2:0] dct12_i_5_address0;
output   dct12_i_5_ce0;
input  [11:0] dct12_i_5_q0;
output  [2:0] dct12_i_6_address0;
output   dct12_i_6_ce0;
input  [11:0] dct12_i_6_q0;
output  [2:0] dct12_i_7_address0;
output   dct12_i_7_ce0;
input  [11:0] dct12_i_7_q0;

reg ap_idle;
reg dct_middle_2_ce0;
reg dct_middle_2_we0;
reg dct_middle_2_ce1;
reg Cr_ce0;
reg Cr_1_ce0;
reg Cr_2_ce0;
reg Cr_3_ce0;
reg Cr_4_ce0;
reg Cr_5_ce0;
reg Cr_6_ce0;
reg Cr_7_ce0;
reg dct12_i_0_ce0;
reg dct12_i_1_ce0;
reg dct12_i_2_ce0;
reg dct12_i_3_ce0;
reg dct12_i_4_ce0;
reg dct12_i_5_ce0;
reg dct12_i_6_ce0;
reg dct12_i_7_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln56_fu_331_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] select_ln56_fu_361_p3;
reg   [3:0] select_ln56_reg_648;
wire   [2:0] trunc_ln56_fu_377_p1;
reg   [2:0] trunc_ln56_reg_653;
wire   [63:0] zext_ln56_fu_381_p1;
reg   [63:0] zext_ln56_reg_658;
wire   [63:0] zext_ln57_fu_387_p1;
reg   [63:0] zext_ln57_reg_678;
reg  signed [11:0] dct12_i_6_load_reg_728;
reg   [5:0] dct_middle_2_addr_reg_738;
reg   [5:0] dct_middle_2_addr_reg_738_pp0_iter2_reg;
reg   [5:0] dct_middle_2_addr_reg_738_pp0_iter3_reg;
reg   [5:0] dct_middle_2_addr_reg_738_pp0_iter4_reg;
reg   [5:0] dct_middle_2_addr_reg_738_pp0_iter5_reg;
reg  signed [7:0] Cr_6_load_reg_774;
reg  signed [11:0] dct12_i_2_load_reg_794;
reg  signed [11:0] dct12_i_3_load_reg_799;
reg  signed [7:0] Cr_2_load_reg_824;
reg  signed [7:0] Cr_3_load_reg_829;
reg  signed [17:0] dct_middle_2_load_reg_844;
reg  signed [17:0] dct_middle_2_load_reg_844_pp0_iter3_reg;
wire   [19:0] mul_ln63_14_fu_481_p2;
reg  signed [19:0] mul_ln63_14_reg_849;
wire   [19:0] mul_ln63_8_fu_499_p2;
reg  signed [19:0] mul_ln63_8_reg_854;
wire   [19:0] mul_ln63_10_fu_505_p2;
reg  signed [19:0] mul_ln63_10_reg_859;
reg   [11:0] tmp_reg_889;
wire    ap_block_pp0_stage0;
wire   [63:0] p_cast_fu_434_p1;
reg   [3:0] jj_fu_76;
wire   [3:0] add_ln57_fu_393_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_jj_load;
reg   [3:0] ii_fu_80;
wire   [3:0] select_ln56_3_fu_369_p3;
reg   [3:0] ap_sig_allocacmp_ii_load;
reg   [6:0] indvar_flatten104_fu_84;
wire   [6:0] add_ln56_fu_337_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten104_load;
wire   [0:0] icmp_ln57_fu_355_p2;
wire   [3:0] add_ln56_2_fu_349_p2;
wire   [5:0] tmp_s_fu_414_p3;
wire   [5:0] select_ln56_5_cast_fu_425_p1;
wire   [5:0] empty_fu_428_p2;
wire  signed [20:0] grp_fu_578_p3;
wire  signed [20:0] grp_fu_596_p3;
wire  signed [20:0] grp_fu_614_p3;
wire  signed [21:0] sext_ln63_21_fu_529_p1;
wire  signed [21:0] sext_ln63_20_fu_526_p1;
wire   [21:0] add_ln63_9_fu_532_p2;
wire  signed [20:0] grp_fu_587_p3;
wire  signed [21:0] grp_fu_605_p3;
wire  signed [22:0] sext_ln63_25_fu_545_p1;
wire  signed [22:0] sext_ln63_23_fu_542_p1;
wire   [22:0] add_ln63_13_fu_548_p2;
wire  signed [23:0] sext_ln63_26_fu_554_p1;
wire  signed [23:0] sext_ln63_22_fu_538_p1;
wire   [23:0] add_ln63_14_fu_558_p2;
wire   [10:0] grp_fu_614_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [18:0] grp_fu_614_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 jj_fu_76 = 4'd0;
#0 ii_fu_80 = 4'd0;
#0 indvar_flatten104_fu_84 = 7'd0;
#0 ap_done_reg = 1'b0;
end

IMG2RLE_mul_8s_12s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 20 ))
mul_8s_12s_20_1_1_U2172(
    .din0(Cr_6_load_reg_774),
    .din1(dct12_i_6_load_reg_728),
    .dout(mul_ln63_14_fu_481_p2)
);

IMG2RLE_mul_8s_12s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 20 ))
mul_8s_12s_20_1_1_U2173(
    .din0(Cr_2_load_reg_824),
    .din1(dct12_i_2_load_reg_794),
    .dout(mul_ln63_8_fu_499_p2)
);

IMG2RLE_mul_8s_12s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 20 ))
mul_8s_12s_20_1_1_U2174(
    .din0(Cr_3_load_reg_829),
    .din1(dct12_i_3_load_reg_799),
    .dout(mul_ln63_10_fu_505_p2)
);

IMG2RLE_mac_muladd_8s_12s_20s_21_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 20 ),
    .dout_WIDTH( 21 ))
mac_muladd_8s_12s_20s_21_4_1_U2175(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Cr_7_q0),
    .din1(dct12_i_7_q0),
    .din2(mul_ln63_14_reg_849),
    .ce(1'b1),
    .dout(grp_fu_578_p3)
);

IMG2RLE_mac_muladd_8s_12s_20s_21_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 20 ),
    .dout_WIDTH( 21 ))
mac_muladd_8s_12s_20s_21_4_1_U2176(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Cr_4_q0),
    .din1(dct12_i_4_q0),
    .din2(mul_ln63_10_reg_859),
    .ce(1'b1),
    .dout(grp_fu_587_p3)
);

IMG2RLE_mac_muladd_8s_12s_18s_21_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 21 ))
mac_muladd_8s_12s_18s_21_4_1_U2177(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Cr_1_q0),
    .din1(dct12_i_1_q0),
    .din2(dct_middle_2_load_reg_844_pp0_iter3_reg),
    .ce(1'b1),
    .dout(grp_fu_596_p3)
);

IMG2RLE_mac_muladd_8s_12s_21s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_12s_21s_22_4_1_U2178(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Cr_5_q0),
    .din1(dct12_i_5_q0),
    .din2(grp_fu_578_p3),
    .ce(1'b1),
    .dout(grp_fu_605_p3)
);

IMG2RLE_mac_muladd_8s_11ns_20s_21_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 20 ),
    .dout_WIDTH( 21 ))
mac_muladd_8s_11ns_20s_21_4_1_U2179(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Cr_q0),
    .din1(grp_fu_614_p1),
    .din2(mul_ln63_8_reg_854),
    .ce(1'b1),
    .dout(grp_fu_614_p3)
);

IMG2RLE_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln56_fu_331_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ii_fu_80 <= select_ln56_3_fu_369_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ii_fu_80 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln56_fu_331_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten104_fu_84 <= add_ln56_fu_337_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten104_fu_84 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln56_fu_331_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            jj_fu_76 <= add_ln57_fu_393_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            jj_fu_76 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        Cr_2_load_reg_824 <= Cr_2_q0;
        Cr_3_load_reg_829 <= Cr_3_q0;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        dct12_i_2_load_reg_794 <= dct12_i_2_q0;
        dct12_i_3_load_reg_799 <= dct12_i_3_q0;
        dct_middle_2_addr_reg_738_pp0_iter2_reg <= dct_middle_2_addr_reg_738;
        dct_middle_2_addr_reg_738_pp0_iter3_reg <= dct_middle_2_addr_reg_738_pp0_iter2_reg;
        dct_middle_2_addr_reg_738_pp0_iter4_reg <= dct_middle_2_addr_reg_738_pp0_iter3_reg;
        dct_middle_2_addr_reg_738_pp0_iter5_reg <= dct_middle_2_addr_reg_738_pp0_iter4_reg;
        dct_middle_2_load_reg_844_pp0_iter3_reg <= dct_middle_2_load_reg_844;
        mul_ln63_10_reg_859 <= mul_ln63_10_fu_505_p2;
        mul_ln63_14_reg_849 <= mul_ln63_14_fu_481_p2;
        mul_ln63_8_reg_854 <= mul_ln63_8_fu_499_p2;
        tmp_reg_889 <= {{add_ln63_14_fu_558_p2[23:12]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Cr_6_load_reg_774 <= Cr_6_q0;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        dct12_i_6_load_reg_728 <= dct12_i_6_q0;
        dct_middle_2_addr_reg_738 <= p_cast_fu_434_p1;
        select_ln56_reg_648 <= select_ln56_fu_361_p3;
        trunc_ln56_reg_653 <= trunc_ln56_fu_377_p1;
        zext_ln56_reg_658[3 : 0] <= zext_ln56_fu_381_p1[3 : 0];
        zext_ln57_reg_678[3 : 0] <= zext_ln57_fu_387_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dct_middle_2_load_reg_844 <= dct_middle_2_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Cr_1_ce0 = 1'b1;
    end else begin
        Cr_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Cr_2_ce0 = 1'b1;
    end else begin
        Cr_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Cr_3_ce0 = 1'b1;
    end else begin
        Cr_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Cr_4_ce0 = 1'b1;
    end else begin
        Cr_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Cr_5_ce0 = 1'b1;
    end else begin
        Cr_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Cr_6_ce0 = 1'b1;
    end else begin
        Cr_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Cr_7_ce0 = 1'b1;
    end else begin
        Cr_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Cr_ce0 = 1'b1;
    end else begin
        Cr_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln56_fu_331_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ii_load = 4'd0;
    end else begin
        ap_sig_allocacmp_ii_load = ii_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten104_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten104_load = indvar_flatten104_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_jj_load = 4'd0;
    end else begin
        ap_sig_allocacmp_jj_load = jj_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct12_i_0_ce0 = 1'b1;
    end else begin
        dct12_i_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct12_i_1_ce0 = 1'b1;
    end else begin
        dct12_i_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct12_i_2_ce0 = 1'b1;
    end else begin
        dct12_i_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct12_i_3_ce0 = 1'b1;
    end else begin
        dct12_i_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct12_i_4_ce0 = 1'b1;
    end else begin
        dct12_i_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct12_i_5_ce0 = 1'b1;
    end else begin
        dct12_i_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct12_i_6_ce0 = 1'b1;
    end else begin
        dct12_i_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct12_i_7_ce0 = 1'b1;
    end else begin
        dct12_i_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        dct_middle_2_ce0 = 1'b1;
    end else begin
        dct_middle_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_middle_2_ce1 = 1'b1;
    end else begin
        dct_middle_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        dct_middle_2_we0 = 1'b1;
    end else begin
        dct_middle_2_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Cr_1_address0 = zext_ln57_reg_678;

assign Cr_2_address0 = zext_ln57_reg_678;

assign Cr_3_address0 = zext_ln57_reg_678;

assign Cr_4_address0 = zext_ln57_reg_678;

assign Cr_5_address0 = zext_ln57_reg_678;

assign Cr_6_address0 = zext_ln57_fu_387_p1;

assign Cr_7_address0 = zext_ln57_fu_387_p1;

assign Cr_address0 = zext_ln57_reg_678;

assign add_ln56_2_fu_349_p2 = (ap_sig_allocacmp_ii_load + 4'd1);

assign add_ln56_fu_337_p2 = (ap_sig_allocacmp_indvar_flatten104_load + 7'd1);

assign add_ln57_fu_393_p2 = (select_ln56_fu_361_p3 + 4'd1);

assign add_ln63_13_fu_548_p2 = ($signed(sext_ln63_25_fu_545_p1) + $signed(sext_ln63_23_fu_542_p1));

assign add_ln63_14_fu_558_p2 = ($signed(sext_ln63_26_fu_554_p1) + $signed(sext_ln63_22_fu_538_p1));

assign add_ln63_9_fu_532_p2 = ($signed(sext_ln63_21_fu_529_p1) + $signed(sext_ln63_20_fu_526_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign dct12_i_0_address0 = zext_ln56_reg_658;

assign dct12_i_1_address0 = zext_ln56_reg_658;

assign dct12_i_2_address0 = zext_ln56_reg_658;

assign dct12_i_3_address0 = zext_ln56_reg_658;

assign dct12_i_4_address0 = zext_ln56_reg_658;

assign dct12_i_5_address0 = zext_ln56_reg_658;

assign dct12_i_6_address0 = zext_ln56_fu_381_p1;

assign dct12_i_7_address0 = zext_ln56_fu_381_p1;

assign dct_middle_2_address0 = dct_middle_2_addr_reg_738_pp0_iter5_reg;

assign dct_middle_2_address1 = p_cast_fu_434_p1;

assign dct_middle_2_d0 = $signed(tmp_reg_889);

assign empty_fu_428_p2 = (tmp_s_fu_414_p3 + select_ln56_5_cast_fu_425_p1);

assign grp_fu_614_p1 = grp_fu_614_p10;

assign grp_fu_614_p10 = dct12_i_0_q0;

assign icmp_ln56_fu_331_p2 = ((ap_sig_allocacmp_indvar_flatten104_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_355_p2 = ((ap_sig_allocacmp_jj_load == 4'd8) ? 1'b1 : 1'b0);

assign p_cast_fu_434_p1 = empty_fu_428_p2;

assign select_ln56_3_fu_369_p3 = ((icmp_ln57_fu_355_p2[0:0] == 1'b1) ? add_ln56_2_fu_349_p2 : ap_sig_allocacmp_ii_load);

assign select_ln56_5_cast_fu_425_p1 = select_ln56_reg_648;

assign select_ln56_fu_361_p3 = ((icmp_ln57_fu_355_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_jj_load);

assign sext_ln63_20_fu_526_p1 = grp_fu_596_p3;

assign sext_ln63_21_fu_529_p1 = grp_fu_614_p3;

assign sext_ln63_22_fu_538_p1 = $signed(add_ln63_9_fu_532_p2);

assign sext_ln63_23_fu_542_p1 = grp_fu_587_p3;

assign sext_ln63_25_fu_545_p1 = grp_fu_605_p3;

assign sext_ln63_26_fu_554_p1 = $signed(add_ln63_13_fu_548_p2);

assign tmp_s_fu_414_p3 = {{trunc_ln56_reg_653}, {3'd0}};

assign trunc_ln56_fu_377_p1 = select_ln56_3_fu_369_p3[2:0];

assign zext_ln56_fu_381_p1 = select_ln56_3_fu_369_p3;

assign zext_ln57_fu_387_p1 = select_ln56_fu_361_p3;

always @ (posedge ap_clk) begin
    zext_ln56_reg_658[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln57_reg_678[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //IMG2RLE_IMG2RLE_Pipeline_L1_L24
